config/routes.rb
require 'sidekiq/web'
# root 'pages#home'
# skip_before_action :authenticate_user!, :only => [:index]

Rails.application.routes.draw do
  resources :destroy_reasons
  # resources :expert_qualifications
  # resources :comission_jobs
  # resources :exam_students
  # resources :registration_places
  resources :except_records
  resources :groups
  resources :download_counts
  resources :shedule_tasks
  resources :shedules
  resources :manuals
  # resources :ates


  concern :downloadable do
    resources :download_counts, only: :create
  end


  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  namespace :admin do
    resources :users
    resources :announcements
    resources :notifications
    resources :services
    root to: "users#index"
  end

  get '/20bdd15b60814bc7b9d87eee7af08cfe/:id', to: 'home#protocol'
  get '/privacy', to: 'home#privacy'
  get '/mouo_statistics', to: 'home#mouo_statistics'
  get '/help', to: 'home#help'
  get '/h5p', to: 'home#h5p'
  get '/terms', to: 'home#terms'
  get '/mssql', to: 'home#mssql'
  get '/recreateemployees', to: 'home#recreateemployees'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # resources :destroy_reasons, only: :index
  get '/destroy_reasons/export', to: 'destroy_reasons#export'
  get '/destroy_reasons/modaledit/:id', to: 'destroy_reasons#modaledit'
  resources :destroy_reasons
  resources :destroy_reasons_imports, only: [:new, :create, :index]

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]

  resources :show_blanks, only: [:index, :show]
  # resources :statistics, only: [:index, :show]
  resources :youtube, only: :show
  resources :tables, only: [:show, :create, :update]

  get '/ates/export', to: 'ates#export'
  get '/ates/modaledit/:id', to: 'ates#modaledit'
  resources :ates
  resources :ates_imports, only: [:new, :create, :index]

  get '/business_entity_types/export', to: 'business_entity_types#export'
  get '/business_entity_types/modaledit/:id', to: 'business_entity_types#modaledit'
  resources :business_entity_types
  resources :business_entity_types_imports, only: [:new, :create, :index]

  get '/human_settlement_types/export', to: 'human_settlement_types#export'
  get '/human_settlement_types/modaledit/:id', to: 'human_settlement_types#modaledit'
  resources :human_settlement_types
  resources :human_settlement_types_imports, only: [:new, :create, :index]

  get '/town_types/export', to: 'town_types#export'
  get '/town_types/modaledit/:id', to: 'town_types#modaledit'
  resources :town_types
  resources :town_types_imports, only: [:new, :create, :index]

  get '/street_types/export', to: 'street_types#export'
  get '/street_types/modaledit/:id', to: 'street_types#modaledit'
  resources :street_types
  resources :street_types_imports, only: [:new, :create, :index]

  get '/building_types/export', to: 'building_types#export'
  get '/building_types/modaledit/:id', to: 'building_types#modaledit'
  resources :building_types
  resources :building_types_imports, only: [:new, :create, :index]

  get '/mouos/export', to: 'mouos#export'
  get '/mouos/modaledit/:id', to: 'mouos#modaledit'
  get '/mouos/create_logins_for_all_mouos', to: 'mouos#create_logins_for_all_mouos'
  resources :mouos
  resources :mouos_imports, only: [:new, :create, :index]

  get '/registration_places/export', to: 'registration_places#export'
  get '/registration_places/modaledit/:id', to: 'registration_places#modaledit'
  resources :registration_places
  resources :registration_places_imports, only: [:new, :create, :index]

  get '/ou_types/export', to: 'ou_types#export'
  get '/ou_types/modaledit/:id', to: 'ou_types#modaledit'
  resources :ou_types
  resources :ou_types_imports, only: [:new, :create, :index]

  get '/ou_kinds/export', to: 'ou_kinds#export'
  get '/ou_kinds/modaledit/:id', to: 'ou_kinds#modaledit'
  resources :ou_kinds
  resources :ou_kinds_imports, only: [:new, :create, :index]

  get '/ous/export', to: 'ous#export'
  get '/ous/create_logins_for_all_ous', to: 'ous#create_logins_for_all_ous'
  get '/ous/get_ous_by_mouo', to: 'ous#get_ous_by_mouo'
  get '/ous/modaledit/:id', to: 'ous#modaledit'
  resources :ous
  resources :ous_imports, only: [:new, :create, :index]

  get '/school_class_profiles/export', to: 'school_class_profiles#export'
  get '/school_class_profiles/modaledit/:id', to: 'school_class_profiles#modaledit'
  resources :school_class_profiles
  resources :school_class_profiles_imports, only: [:new, :create, :index]

  get '/groups/export', to: 'groups#export'
  get '/groups/modaledit/:id', to: 'groups#modaledit'
  resources :groups
  resources :groups_imports, only: [:new, :create, :index]

  get '/citizenships/export', to: 'citizenships#export'
  get '/citizenships/modaledit/:id', to: 'citizenships#modaledit'
  resources :citizenships
  resources :citizenships_imports, only: [:new, :create, :index]

  get '/document_types/export', to: 'document_types#export'
  get '/document_types/modaledit/:id', to: 'document_types#modaledit'
  resources :document_types
  resources :document_types_imports, only: [:new, :create, :index]

  get '/education_document_types/export', to: 'education_document_types#export'
  get '/education_document_types/modaledit/:id', to: 'education_document_types#modaledit'
  resources :education_document_types
  resources :education_document_types_imports, only: [:new, :create, :index]

  get '/limited_facilities_groups/export', to: 'limited_facilities_groups#export'
  get '/limited_facilities_groups/modaledit/:id', to: 'limited_facilities_groups#modaledit'
  resources :limited_facilities_groups
  resources :limited_facilities_groups_imports, only: [:new, :create, :index]

  get '/regions/export', to: 'regions#export'
  get '/regions/modaledit/:id', to: 'regions#modaledit'
  resources :regions
  resources :regions_imports, only: [:new, :create, :index]

  get '/gek_issues/export', to: 'gek_issues#export'
  get '/gek_issues/modaledit/:id', to: 'gek_issues#modaledit'
  resources :gek_issues
  resources :gek_issues_imports, only: [:new, :create, :index]

  get '/study_forms/export', to: 'study_forms#export'
  get '/study_forms/modaledit/:id', to: 'study_forms#modaledit'
  resources :study_forms
  resources :study_forms_imports, only: [:new, :create, :index]

  get '/attestation_forms/export', to: 'attestation_forms#export'
  get '/attestation_forms/modaledit/:id', to: 'attestation_forms#modaledit'
  resources :attestation_forms
  resources :attestation_forms_imports, only: [:new, :create, :index]

  get '/special_seatings/export', to: 'special_seatings#export'
  get '/special_seatings/modaledit/:id', to: 'special_seatings#modaledit'
  resources :special_seatings
  resources :special_seatings_imports, only: [:new, :create, :index]

  get '/ege_participant_categories/export', to: 'ege_participant_categories#export'
  get '/ege_participant_categories/modaledit/:id', to: 'ege_participant_categories#modaledit'
  resources :ege_participant_categories
  resources :ege_participant_categories_imports, only: [:new, :create, :index]

  get '/exam_students/exam_students_vyverka', to: 'exam_students#exam_students_vyverka'
  resources :exam_students

  get '/students/set_gia_admission_to_all', to: 'students#set_gia_admission_to_all'
  get '/students/export', to: 'students#export'
  get '/students/modaledit/:id', to: 'students#modaledit'
  get '/students/name_norming', to: 'students#name_norming'
  get '/student/exam_students', to: 'exam_students#index'
  get 'new_student_exam_student', to: 'exam_students#new'
  get '/students/create_logins_for_all_students', to: 'students#create_logins_for_all_students'
  resources :students
  resources :students_imports, only: [:new, :create, :index]
  post 'students/:id', to: 'students#show'

  get '/composition_types/export', to: 'composition_types#export'
  get '/composition_types/modaledit/:id', to: 'composition_types#modaledit'
  resources :composition_types
  resources :composition_types_imports, only: [:new, :create, :index]

  get '/compositions/export', to: 'compositions#export'
  get '/compositions/modaledit/:id', to: 'compositions#modaledit'
  resources :compositions
  resources :compositions_imports, only: [:new, :create, :index]

  get '/subjects/export', to: 'subjects#export'
  get '/subjects/modaledit/:id', to: 'subjects#modaledit'
  resources :subjects
  resources :subjects_imports, only: [:new, :create, :index]

  get '/exams/export', to: 'exams#export'
  get '/exams/modaledit/:id', to: 'exams#modaledit'
  resources :exams
  resources :exams_imports, only: [:new, :create, :index]

  get '/exam_waves/export', to: 'exam_waves#export'
  get '/exam_waves/modaledit/:id', to: 'exam_waves#modaledit'
  resources :exam_waves
  resources :exam_waves_imports, only: [:new, :create, :index]

  get '/exam_types/export', to: 'exam_types#export'
  get '/exam_types/modaledit/:id', to: 'exam_types#modaledit'
  resources :exam_types
  resources :exam_types_imports, only: [:new, :create, :index]

  get '/except_records/export', to: 'except_records#export'
  get '/except_records/modaledit/:id', to: 'except_records#modaledit'
  resources :except_records
  resources :except_records_imports, only: [:new, :create, :index]

  get '/ege_statements/new_ege', to: 'ege_statements#new_ege'
  get '/ege_statements/new_oge', to: 'ege_statements#new_oge'
  get '/ege_statements/new_gve9', to: 'ege_statements#new_gve9'
  get '/ege_statements/new_gve11', to: 'ege_statements#new_gve11'
  get '/ege_statements/export', to: 'ege_statements#export'
  get '/ege_statements/modaledit/:id', to: 'ege_statements#modaledit'
  get '/ege_statements/:id/import', to: 'ege_statements#import'
  get '/ege_statements/:id/import_create_student', to: 'ege_statements#import_create_student'
  get '/ege_statements/import_create_exams', to: 'ege_statements#import_create_exams'

app/models/cbt_user_test_question.rb
class CbtUserTestQuestion < ApplicationRecord
  acts_as_paranoid
  has_paper_trail

  #============================VALIDATION START================================
  # name, code, created_at, updated_at, short_name, fisgia9code, fisgia11code

  #=============================VALIDATION END=================================

  # has_many :ous
  # has_many :shedule_tasks
  # has_many :monitoring_objectivity_ates
  # has_many :appeal_stations
  belongs_to :cbt_user_test
  belongs_to :cbt_question

  def self.search(search)
    if search
      where('cast(id as varchar) LIKE ?', "%#{search}%")
    end
  end

  def to_s
    name
  end

  def set_property(prop_name, prop_value)
    self.send("#{prop_name}=",prop_value)
    # puts("#{prop_name} : #{prop_value}")
    # puts self.inspect
  end

  self.per_page = 1

  # set per_page globally
  WillPaginate.per_page = 1

end

app/controllers/cbt_user_test_questions_controller.rb
class CbtUserTestQuestionsController < ApplicationController
  load_and_authorize_resource :instance_name => :item
  before_action :authenticate_user!

  def index
    @cbt_user_test_questions = CbtUserTestQuestion.accessible_by(current_ability).paginate(page: params[:page]).order('id DESC')
    if current_user.admin?
      if !params[:search].nil?
        @cbt_user_test_questions = CbtUserTestQuestion.accessible_by(current_ability).search(params[:search]).paginate(page: params[:page]).order('id DESC')
      end
    else
      if !params[:search].nil?
        @cbt_user_test_questions = CbtUserTestQuestion.accessible_by(current_ability).search(params[:search]).paginate(page: params[:page]).order('id DESC')
      end
    end
  end

  def export
    @cbt_user_test_questions = CbtUserTestQuestion.accessible_by(current_ability).order('id DESC')
    respond_to do |format|
      format.xlsx{
        response.headers['Content-Disposition'] = "attachment; filename=#{'cbt_user_test_questions_list_' + DateTime.now.getlocal.to_s.gsub(' ', '-').gsub(':', '.') + '.xlsx'}"
      }
    end
  end

  def new
    @cbt_user_test_question = CbtUserTestQuestion.new
    if !@cbt_user_test_question.nil?
       render :edit
    else
       flash[:success] = t("cbt_user_test_questions.errors.cant_create_new")
       redirect_to :action => 'index'
    end
  end

  def show
    @cbt_user_test_question = CbtUserTestQuestion.accessible_by(current_ability).find(params[:id])
    @previous = CbtUserTestQuestion.accessible_by(current_ability).where("id < " + @cbt_user_test_question.id.to_s).order("id DESC").first
    @next = CbtUserTestQuestion.accessible_by(current_ability).where("id > " + @cbt_user_test_question.id.to_s).order("id ASC").first
    @cbt_user_test_questions = CbtUserTestQuestion.accessible_by(current_ability).all.order('id DESC')
    if can? :view, @cbt_user_test_question
      render :action => 'show'
    end
  end

  def create
    @cbt_user_test_question = CbtUserTestQuestion.new(cbt_user_test_question_params)
    if @cbt_user_test_question.save
      redirect_to :action => 'index'
    else
      render :action => 'new'
    end
  end

  def edit
    @cbt_user_test_question = CbtUserTestQuestion.accessible_by(current_ability).find(params[:id])
    respond_to do |format|
      format.html
      format.json { respond_modal_with @cbt_user_test_question }
    end
  end

  def modaledit
    @cbt_user_test_question = CbtUserTestQuestion.accessible_by(current_ability).find(params[:id])
    respond_to do |format|
      format.html { render :partial => 'form' }
      format.json { respond_modal_with @cbt_user_test_question }
    end
  end

  def delete
    # flash[:success] = t("ates.notice.updated")
    CbtUserTestQuestion.accessible_by(current_ability).find(params[:id]).destroy
    return
  end

  def destroy
    @cbt_user_test_question = CbtUserTestQuestion.accessible_by(current_ability).find(params[:id])
    @cbt_user_test_question.destroy
    respond_to do |format|
      format.html { redirect_to cbt_user_test_questions_url, notice: t("cbt_user_test_questions.notice.destroyed") }
      format.json { head :no_content }
    end
    # redirect :action => 'index'
  end

  def update
    @cbt_user_test_question = CbtUserTestQuestion.accessible_by(current_ability).find(params[:id])

    if !params[:mark_k].nil?
      i = 0
      @cbt_user_test_question.user_answer = ''

      params[:mark_k].each do |m|
        i = i + 1
        if @cbt_user_test_question.cbt_question.cbt_answer_type.name == 'Отметки по критериям'
          if i > 1
            @cbt_user_test_question.user_answer += '#'
          end
          ball = m[1]
          # puts(m[1])
          if !ball.nil?
            ball = ball.gsub(',', '.').gsub(' ', '')
            if !(begin !!Float(ball) rescue false end)
              ball = 'X'
            end
          end
          ball = 'X' if ball.nil?
          ball = 'X' if ball == ''
          # puts (ball)
          # puts (@mark.balls_list)
          @cbt_user_test_question.user_answer+= ball.to_s
        elsif @cbt_user_test_question.cbt_question.cbt_answer_type.name == 'Выбор одного варианта из многих'
          @cbt_user_test_question.user_answer = m[1]
        elsif @cbt_user_test_question.cbt_question.cbt_answer_type.name == 'Выбор нескольких вариантов из многих'
          if m[1] == '1'
            if @cbt_user_test_question.user_answer != ''
              @cbt_user_test_question.user_answer += '#'
            end
            @cbt_user_test_question.user_answer += m[0]
          end
        elsif @cbt_user_test_question.cbt_question.cbt_answer_type.name == 'Свободный краткий ответ'
          # puts("here is m: #{m.inspect}")
          # puts("here is m[0]: #{m[0]}")
          # puts("here is m[1]: #{m[1]}")
          @cbt_user_test_question.user_answer = m[1]
        else
          @cbt_user_test_question.user_answer = 'Не понятен тип ответа'
        end

      end
    else
      @cbt_user_test_question.user_answer = nil
    end

    @cbt_user_test_question.end_time = Time.now.zone

    if @cbt_user_test_question.update cbt_user_test_question_params
      respond_to do |format|
        format.html {
          flash[:success] = t("cbt_user_test_questions.notice.updated")
          redirect_to "/cbt_home/get_user_test_question/#{@cbt_user_test_question.id}"
        }
        format.json { render :json => { :status => 200 }}
      end
    else
      respond_to do |format|
        format.html {
          flash[:error] = ""
          @cbt_user_test_question.errors.each do |er|
            flash[:error] = ((flash[:error] || '') + t("cbt_user_test_questions." + er.attribute.to_s) + ': ' + t("cbt_user_test_questions.errors." + er.type.to_s)) + "; "
          end
          redirect_to "/cbt_home/get_user_test_question/#{@cbt_user_test_question.id}"
        }
        format.json { respond_with_bip(@cbt_user_test_question) }
      end
    end

  end

  def cbt_user_test_question_params
    params.require(:cbt_user_test_question).permit(:cbt_user_test_id, :cbt_question_id, :start_time, :end_time, :user_answer, :primary_mark, :marked, :sort_by)
  end

  private
  def undo_link
    view_context.link_to("undo", revert_version_path(@cbt_user_test_question.versions.scoped.last), :method => :post)
  end

end

app/views/cbt_user_test_questions/_edit.html.haml
%html
  %head
    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "content-type"}/
  %body
    %h4
      .text3d= t("cbt_user_test_questions.actions.edit")
    = form_for @cbt_user_test_question do |f|
      .form-group
        .alert.alert-info{:role => "alert"}
          ="Внимание! На данной странице"
          %b
            ="не выполняется"
          ="автоматическое сохранение."
          %br
          ="Вы можете в любой момент нажать «Вернуться», чтобы отменить все сделанные изменения."
          %br
          ="Для применения изменений, служит кнопка «Сохранить»."
        -#name, code, created_at, updated_at, short_name, fisgia9code, fisgia11code

        %table.table-borderless
          %tr
            %td{:style=>"vertical-align: top;"}
              .card
                .card-header
                  Карточка типа образовательной организации
                .card-body
                  %h5.card-title Тип образовательной организации
                  %p.card-text
                    %table.table-bordered.table-striped
                      %tr
                        %th= t("cbt_user_test_questions.code")
                        %td= f.text_field :code, autofocus: false, placeholder: t("cbt_user_test_questions.code"), class: 'form-control'
                      %tr
                        %th= t("cbt_user_test_questions.name")
                        %td= f.text_field :name, autofocus: false, placeholder: t("cbt_user_test_questions.name"), class: 'form-control'
                      %tr
                        %th= t("cbt_user_test_questions.short_name")
                        %td= f.text_field :short_name, autofocus: false, placeholder: t("cbt_user_test_questions.short_name"), class: 'form-control'
                      %tr
                        %th= t("cbt_user_test_questions.fisgia9code")
                        %td= f.number_field :fisgia9code, autofocus: false, placeholder: t("cbt_user_test_questions.fisgia9code"), class: 'form-control'
                      %tr
                        %th= t("cbt_user_test_questions.fisgia11code")
                        %td= f.number_field :fisgia11code, autofocus: false, placeholder: t("cbt_user_test_questions.fisgia11code"), class: 'form-control'
                      %tr
                        %th= t("cbt_user_test_questions.sort_by")
                        %td= f.number_field :sort_by, autofocus: false, placeholder: t("cbt_user_test_questions.sort_by"), class: 'form-control'

              %p
                .form-actions
                  = f.submit @cbt_user_test_question.new_record? ? t("buttons.create") : t("buttons.save"), :class => 'btn btn-primary btn-with-tooltip',"data-original-title" => t("messages.tooltips.save"),"data-placement" => "bottom"
                  = link_to t('buttons.back'), :back, :class => 'btn btn-primary btn-with-tooltip',"data-original-title" => t("messages.tooltips.back")
            %td{:style=>"vertical-align: top;"}
              - if @cbt_user_test_question.errors.any?
                #error_explanation
                  .alert.alert-danger.shadow
                    %h4= "#{I18n.t :error, count: @cbt_user_test_question.errors.count} не #{I18n.t :pozvol, count: @cbt_user_test_question.errors.count} сохранить запись:"
                  .shadow-sm.p-3.mb-5.bg-white.rounded
                    %ul
                      - @cbt_user_test_question.errors.full_messages.each do |message|
                        %li= message

app/views/cbt_user_test_questions/_list.html.haml
-if !@cbt_user_test_questions.nil?
  %p
    = I18n.t :cbt_user_test_question, count: @cbt_user_test_questions.count

-if @cbt_user_test_questions.count > 20
  .apple_pagination
    = will_paginate @cbt_user_test_questions

-#:cbt_user_test_id, :cbt_question_id, :start_time, :end_time, :user_answer, :primary_mark, :marked, :sort_by
%p
  %table.styled-table{:style=>"width:100%;"}
    %thead
      %th= t("cbt_user_test_questions.code")
      %th= "Код теста пользователя"
      %th= "Код теста вопроса"
      %th= "Начало"
      %th= "Конец"
      %th= "Ответ пользователя"
      %th= "Первичный балл"
      %th= "Пометка"
      %th= "Порядок сортировки"
      -if current_user.admin?
        %th= t("cbt_user_test_questions.actions.title")
    %tbody
      -@cbt_user_test_questions.each do |row|
        %tr
          %td= row.id.to_s
          %td= link_to row.cbt_user_test.to_s, cbt_user_test_question_path(row)
          %td= link_to row.cbt_question.to_s, cbt_user_test_question_path(row)
          %td= row.start_time
          %td= row.end_time
          %td= row.user_answer
          %td= row.primary_mark
          %td= row.marked
          %td= row.sort_by
          -if current_user.admin?
            %td
              - if can? :edit, row
                = link_to edit_cbt_user_test_question_path(row) do
                  = image_tag('pencil.png', size: "24", :tooltip=>t("edit"))
              - if (can? :edit, row) and  (can? :delete, row)
                = "  "
              - if can? :delete, row
                = link_to cbt_user_test_question_path(row), :method => :delete,  data: { confirm: t('cbt_user_test_questions.delete_confirm')} do
                  = image_tag('trash.png', size: "24", :tooltip=>t("delete"))

-if @cbt_user_test_questions.count > 20
  .apple_pagination
    = will_paginate @cbt_user_test_questions

app/views/cbt_user_test_questions/edit.html.haml
= render :partial => 'edit', :locals => {:legend => t(".title")}

app/views/cbt_user_test_questions/new.html.haml
= render :partial => 'edit', :locals => {:legend => t(".title")}

app/views/cbt_user_test_questions/show.html.haml
#carouselExampleIndicators.carousel.slide{"data-ride" => "carousel"}
  %ol.carousel-indicators
  .carousel-inner
    .carousel-item.active
      -begin
        %h2{:align => 'center'}=@cbt_user_test_question.name.to_s
      -rescue
        %h2{:align => 'center'}=""
  -if !@previous.nil?
    %a.carousel-control-prev{"data-slide" => "prev", :href => "/cbt_user_test_questions/" + @previous.id.to_s, :role => "button"}
      %span.carousel-control-prev-icon{"aria-hidden" => "true"}
      %p=@previous.name[0..10]+'...'.to_s
  -if !@next.nil?
    %a.carousel-control-next{"data-slide" => "next", :href => "/cbt_user_test_questions/" + @next.id.to_s, :role => "button"}
      %p=@next.name[0..10]+'...'.to_s
      %span.carousel-control-next-icon{"aria-hidden" => "true"}

.alert.alert-info{:role => "alert"}
  - if can? :edit, @ate
    ="Внимание! На данной странице возможен как просмотр, так и редактирование отдельных полей (через двойной щелчок по полю), при этом "
    %b
      ="производится автоматическое сохранение"
    =" каждого отдельного поля. "
    ="В связи с этим, если в карточке есть хотя бы одно неверное заполненное поле, то изменения не сохраняются."
    %br
    ="Чтобы изменить несколько полей, следует перейти в режим редактирования всей записи по кнопке «Редактировать»."
    ="Поля, заблокированные для редактирования, помечены серым цветом."
  -else
    ="Редактирование данной записи заблокировано."
%table
  -if current_user.admin?
    %tr
      %th= t("cbt_user_test_questions.guid")
      %td= best_in_place @ate, :guid
  - else
    %tr
      %th= t("cbt_user_test_questions.guid")
      %td{bgcolor: '#C0C0C0'}= @cbt_user_test_question.guid.to_s
  %tr
    %th= t("cbt_user_test_questions.code")
    - if can? :edit, @ate
      %td= best_in_place @ate, :code
    - else
      %td{bgcolor: '#C0C0C0'}=@cbt_user_test_question.code.to_s
  %tr
    %th= t("cbt_user_test_questions.full_name")
    - if can? :edit, @ate
      %td= best_in_place @ate, :name
    - else
      %td{bgcolor: '#C0C0C0'}=@cbt_user_test_question.name.to_s
  %tr
    %th= t("cbt_user_test_questions.district")
    - if can? :edit, @ate
      %td= best_in_place @ate, :district
    - else
      %td{bgcolor: '#C0C0C0'}=@cbt_user_test_question.district.to_s
  %tr
    %th
      = t("cbt_user_test_questions.low_address")
      = "(поле не обязательно)"
    - if can? :edit, @ate
      %td= best_in_place @ate, :low_address
    - else
      %td{bgcolor: '#C0C0C0'}=@cbt_user_test_question.low_address.to_s
  %tr
    %th
      = t("cbt_user_test_questions.address")
      = "(поле не обязательно)"
    - if can? :edit, @ate
      %td= best_in_place @ate, :address
    - else
      %td{bgcolor: '#C0C0C0'}=@cbt_user_test_question.address.to_s
  %tr
    %th= t("cbt_user_test_questions.charge_fio")
    - if can? :edit, @ate
      %td= best_in_place @ate, :charge_fio
    - else
      %td{bgcolor: '#C0C0C0'}=@cbt_user_test_question.charge_fio.to_s
  %tr
    %th= t("cbt_user_test_questions.phones")
    - if can? :edit, @ate
      %td= best_in_place @ate, :phones
    - else
      %td{bgcolor: '#C0C0C0'}=@cbt_user_test_question.phones.to_s
  %tr
    %th= t("cbt_user_test_questions.email")
    - if can? :edit, @ate
      %td= best_in_place @ate, :email
    - else
      %td{bgcolor: '#C0C0C0'}=@cbt_user_test_question.email.to_s
  %tr
    %th= t("cbt_user_test_questions.www")
    - if can? :edit, @ate
      %td= best_in_place @ate, :www
    - else
      %td{bgcolor: '#C0C0C0'}=@cbt_user_test_question.www.to_s

-if @cbt_user_test_questions.count > 1
  .apple_pagination
    .pagination{:role => "navigation"}
      %span.previous_page.disabled
      - i = 1
      - lm = (@cbt_user_test_questions.count / 25).to_i
      - lmk = (@cbt_user_test_question.code.to_i / lm).to_i
      -if @cbt_user_test_questions.count > 3
        -@cbt_user_test_questions.each do |r|
          -if ((r.code.to_i == @cbt_user_test_questions.first.code.to_i) or (r.code.to_i == @cbt_user_test_questions.last.code.to_i)) and (r.code.to_i != @cbt_user_test_question.code.to_i)
            %a{:href => r.id.to_s}
              =r.code.to_s
          -else
            -if r.code.to_i == @cbt_user_test_question.code.to_i
              %em.current{"aria-current" => "page"}
                =r.code.to_s
            -else
              -if ((r.code.to_i >= @cbt_user_test_question.code.to_i - 8) and (r.code.to_i <= @cbt_user_test_question.code.to_i + 8)) or r.code.to_i % lm == 0
                %a{:href => r.id.to_s}
                  =r.code.to_s
      %span.next_page.disabled

%div
  %hr
    = link_to cbt_user_test_questions_path, :class => "btn btn-primary btn-mini" do
      = bootstrap_icon "card-list", width: 15, height: 15, fill: "yellow"
      = " Вернуться к списку АТЕ "
    \ 
    - if can? :edit, @ate
      = link_to edit_ate_path(@ate), :class => "btn btn-primary btn-mini" do
        = bootstrap_icon "pencil", width: 15, height: 15, fill: "yellow"
        = " Редактировать "